# Generated by Django 3.0.6 on 2020-05-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sensor_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=50)),
                ('stype', models.CharField(max_length=50)),
                ('slocation', models.CharField(max_length=50)),
            ],
        ),
    ]
