FROM ubuntu:latest
RUN apt-get -y update
RUN apt-get -y install python3 
RUN apt-get -y install python3-pip 
RUN pip3 install confluent-kafka
RUN pip3 install psutil
RUN pip3 install schedule
RUN pip3 install DateTime
RUN pip3 install glob3
RUN apt-get -y install sqlite3
WORKDIR /opt
COPY ./logging /opt/logging
CMD ["sh","-c","python3 -u /opt/logging/logging.py"]
