version: '3'

services:
    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        ports: 
            - 8000:8000
    zookeeper:
        image: wurstmeister/zookeeper
        hostname: zookeeper
        ports:
            - "2181:2181"
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ALLOW_ANONYMOUS_LOGIN: 'yes'
        #     ZOOKEEPER_TICK_TIME: 2000

    kafka:
        image: wurstmeister/kafka
        # hostname: broker-1
        # depends_on:
        #     - zookeeper
        ports:
            - "9092:9092"
        environment:
            KAFKA_ADVERTISED_HOST_NAME: localhost
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT: //kafka:29092,PLAINTEXT_HOST://localhost:9092
            ALLOW_PLAINTEXT_LISTENER: 'yes'
            