# Generated by Django 3.0.6 on 2020-07-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_id', models.IntegerField()),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('app_name', models.CharField(max_length=50)),
                ('service', models.CharField(max_length=50)),
                ('datetime', models.DateField()),
            ],
        ),
    ]
