# Generated by Django 3.0.6 on 2020-07-11 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('action_notification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='notify_id',
        ),
    ]
