# Generated by Django 3.0.6 on 2020-07-11 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('action_notification', '0002_remove_notifications_notify_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='datetime',
        ),
    ]
