# Generated by Django 3.0.6 on 2020-07-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action_notification', '0004_auto_20200712_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='phone_num',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='datetime',
            field=models.CharField(default='2020-07-13 13:13:40.090643', max_length=50),
        ),
    ]
