# Generated by Django 3.0.6 on 2020-07-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action_notification', '0005_auto_20200713_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='phone_num',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='lastname',
        ),
        migrations.AlterField(
            model_name='notifications',
            name='datetime',
            field=models.CharField(default='2020-07-14 06:28:06.375153', max_length=50),
        ),
    ]
