# Generated by Django 3.0.6 on 2020-07-16 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action_notification', '0006_auto_20200714_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='urgency',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='datetime',
            field=models.CharField(default='2020-07-16 12:04:25.323117', max_length=50),
        ),
    ]
