# Generated by Django 3.0.6 on 2020-07-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action_notification', '0007_auto_20200716_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='datetime',
            field=models.CharField(default='2020-07-18 07:28:39.674623', max_length=50),
        ),
    ]
