# Generated by Django 3.0.6 on 2020-07-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action_notification', '0009_auto_20200718_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='datetime',
            field=models.CharField(default='2020-07-25 17:40:47.341300', max_length=50),
        ),
    ]
