# Generated by Django 3.0.6 on 2020-07-25 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action_notification', '0010_auto_20200725_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='datetime',
            field=models.CharField(default='2020-07-25 17:43:52.286360', max_length=50),
        ),
    ]
