# Generated by Django 3.0.6 on 2020-05-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_model',
            name='app_email',
            field=models.EmailField(default='xyz@abc.com', max_length=254),
        ),
    ]
