# Generated by Django 3.0.6 on 2020-05-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_info', '0002_app_model_app_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='filemap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_files', models.FileField(upload_to='')),
                ('filename', models.CharField(max_length=50)),
            ],
        ),
    ]
