# Generated by Django 3.0.6 on 2020-05-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_info', '0003_filemap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemap',
            name='app_files',
            field=models.CharField(max_length=50),
        ),
    ]
