# Generated by Django 3.0.6 on 2020-05-27 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_info', '0004_auto_20200527_1910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filemap',
            old_name='app_files',
            new_name='app_name',
        ),
    ]
